ALTER TABLE Orders ADD COLUMN address VARCHAR(255);
ALTER TABLE Orders ADD COLUMN city VARCHAR(100);
ALTER TABLE Orders ADD COLUMN zip_code VARCHAR(20);
ALTER TABLE Product ADD COLUMN subtitle VARCHAR(255);
